### ISSUE TITLE
Repositories with hyphens in the local file&folder path prevent PDF and PS generation

### ISSUE THREAD

**Issue by herp-a-derp** [crc8/GitVersionTree#3]
Basically what the title says.

I have a repository that has a hyphen in the path-name, such as:  
`C:/Derp/Repo-R1`

It successfully generates a `.dot` (and a `.log`) file, but no PDF/PS.

**Comment by crc8** [comment]
This was cause by same issue with https://github.com/crc8/GitVersionTree/pull/1

Build from that commit will fix the issue.

**Comment by ChrisGWarp** [comment]
For those of us who do not have (or want to use) VS, can you please ship a .EXE with that commit applied? Thanks.
-Chris
